'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SearchToolUserControl

	'''<summary>
	'''divSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''h2_SearchTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents h2_SearchTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''li_SearchMode_FlightPlusHotel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents li_SearchMode_FlightPlusHotel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''li_SearchMode_Hotel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents li_SearchMode_Hotel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''li_SearchMode_Flight control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents li_SearchMode_Flight As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hidSearchMode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidSearchMode As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''ddlDepartingFromID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlDepartingFromID As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlArrivingAtID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlArrivingAtID As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlDuration control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlDuration As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlMealBasisID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlMealBasisID As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlRooms control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlRooms As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlAdults_1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlAdults_1 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildren_1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildren_1 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlInfants_1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlInfants_1 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_1_1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_1_1 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_1_2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_1_2 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_1_3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_1_3 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_1_4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_1_4 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlAdults_2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlAdults_2 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildren_2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildren_2 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlInfants_2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlInfants_2 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_2_1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_2_1 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_2_2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_2_2 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_2_3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_2_3 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_2_4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_2_4 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlAdults_3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlAdults_3 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildren_3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildren_3 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlInfants_3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlInfants_3 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_3_1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_3_1 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_3_2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_3_2 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_3_3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_3_3 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlChildAge_3_4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlChildAge_3_4 As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''btnSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSearch As Global.System.Web.UI.HtmlControls.HtmlInputButton

	'''<summary>
	'''hidBookAheadDays control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidBookAheadDays As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidSingleRoomLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidSingleRoomLabel As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidMultiRoomLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidMultiRoomLabel As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidDepartureDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidDepartureDate As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidReturnDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidReturnDate As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidCachedSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCachedSearch As Global.Intuitive.WebControls.Hidden
End Class
