'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class res
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iVectorWidgets.res", GetType(res).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''	&lt;xsl:param name=&quot;TradeContactEmail&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divAlternateEmail&quot; class=&quot;alternate-email box primary&quot;&gt;
    '''			
    '''			&lt;div class=&quot;boxTitle&quot;&gt;
    '''				&lt;h2 ml=&quot;Alternate Email&quot;&gt;Confirmation Email&lt;/h2&gt;
    '''			&lt;/div&gt;
    '''			
    '''			&lt;p&gt;
    '''				&lt;trans ml=&quot;Alternate Email&quot;&gt;Your documentation will be sent to&lt;/ [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property AlternateEmail() As String
        Get
            Return ResourceManager.GetString("AlternateEmail", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PriceFormat&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divBaggage&quot; class=&quot;box primary&quot;&gt;
    '''
    '''			&lt;input type=&quot;hidden&quot; id=&quot;hidBaggagePax&quot;  [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Baggage() As String
        Get
            Return ResourceManager.GetString("Baggage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl &quot;/&gt;
    '''	
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ExcludeSubtotals&quot; /&gt;	
    '''	&lt;xsl:param name=&quot;PassengerBreakdown&quot; /&gt;
    '''	&lt;xsl:param name=&quot;HideBaggage&quot; /&gt;
    '''	&lt;xsl:param name=&quot;TotalComponents&quot; /&gt;
    '''	
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Basket() As String
        Get
            Return ResourceManager.GetString("Basket", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
    '''
    '''	&lt;xsl:param name=&quot;TradeSite&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SummaryTitle&quot; /&gt;
    '''	&lt;xsl:param name=&quot;DetailedPriceBreakdown&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SummaryIncludeDates&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PriceFormat&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SubText&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divConfirmation&quot;&gt;
    '''
    '''			&lt;xsl:for-each select=&quot;GetBoo [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property BookingConfirmation() As String
        Get
            Return ResourceManager.GetString("BookingConfirmation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
    '''
    '''	&lt;xsl:param name=&quot;BookingReference&quot; /&gt;
    '''	&lt;xsl:param name=&quot;HeaderText&quot; /&gt;
    '''	&lt;xsl:param name=&quot;BookingDocument&quot; /&gt;
    '''  &lt;xsl:param name=&quot;HideDocuments&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divConfirmationPrint&quot; class=&quot;sidebarBox primary&quot;&gt;
    '''
    '''			&lt;div class=&quot;boxTitle&quot;&gt;
    '''				&lt;h2&gt;
    '''					&lt;xsl:choose&gt;
    '''						&lt;xsl:when t [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property BookingConfirmationPrint() As String
        Get
            Return ResourceManager.GetString("BookingConfirmationPrint", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''&lt;xsl:param name=&quot;BaseURL&quot; /&gt;
    '''&lt;xsl:param name=&quot;BookingPathway&quot; select=&quot;&apos;false&apos;&quot;/&gt;
    '''&lt;xsl:param name=&quot;CurrentPage&quot; /&gt;
    '''&lt;xsl:param name=&quot;SearchMode&quot; /&gt;
    '''&lt;xsl:param name=&quot;ExtraTypes&quot; /&gt;
    '''&lt;xsl:param name=&quot;UseAccessibleURLs&quot; /&gt;
    '''&lt;xsl:param name=&quot;SeparateXML&quot; /&gt;
    '''&lt;xsl:param name=&quot;UseNumbers&quot; /&gt;
    '''&lt;xsl:param name=&quot;ObjectType [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Breadcrumbs() As String
        Get
            Return ResourceManager.GetString("Breadcrumbs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
    '''    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
    '''&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
    '''	&lt;xsl:param name=&quot;SellingCurrencySymbol&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;input type=&quot;hidden&quot; id=&quot;hidCancelComponent_SellingCurrencySymbol&quot; value=&quot;{$SellingCurrencySymbol}&quot; /&gt;
    '''		&lt;input type=&quot;hidden&quot; id=&quot;hidCancelComponent_BookingReference&quot; value=&quot;{Cancellatio [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property CancelComponentPopup() As String
        Get
            Return ResourceManager.GetString("CancelComponentPopup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot;  /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot;  /&gt;
    '''	&lt;xsl:param name=&quot;DateToday&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SearchMode&quot; /&gt;
    '''	&lt;xsl:param name=&quot;IntroductionOverride&quot; /&gt;
    '''
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''		&lt;xsl:if test=&quot;count(/BookingBasket/PreBookResponse/PropertyBookings/PropertyPreBookRespon [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property CancellationCharges() As String
        Get
            Return ResourceManager.GetString("CancellationCharges", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SubTitle&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Theme&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CSSClassOverride&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SearchMode&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Aut [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property CarHire() As String
        Get
            Return ResourceManager.GetString("CarHire", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Theme&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CSSClassOverride&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SearchMode&quot; /&gt;
    '''	&lt;xsl:param name=&quot;AutomaticSearchType&quot; /&gt;
    '''	&lt;xsl:para [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property CarHireResults() As String
        Get
            Return ResourceManager.GetString("CarHireResults", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Theme&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SelectedFlightToken&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Template&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Passengers&quot; /&gt;
    '''    &lt;xsl:param name=&quot;CMSBaseURL&quot; /&gt;
    '''	&lt;xsl:par [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property ChangeFlight() As String
        Get
            Return ResourceManager.GetString("ChangeFlight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;IncludeContactInformation&quot; /&gt;
    '''	&lt;xsl:param name=&quot;IncludeMainImage&quot; /&gt;
    '''	&lt;xsl:param name=&quot;IncludeBreadcrumbs&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ShowHeading&quot;/&gt;
    '''	&lt;xsl:param name=&quot;WarningText&quot;/&gt;
    '''	&lt;xsl:param name=&quot;Cap [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property ContactUs() As String
        Get
            Return ResourceManager.GetString("ContactUs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;RequiresAccepting&quot; /&gt;
    '''  &lt;xsl:param name=&quot;HideCookieMessage&quot;/&gt;
    '''  
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div class=&quot;cookieCompliance&quot; id=&quot;divCookieCompliance&quot;&gt;
    '''
    '''			&lt;div class=&quot;container&quot;&gt;
    '''				
    '''				&lt;p&gt;
    '''					&lt;xsl:value-of select =&quot;CookieCompliance/Message&quot;/&gt;
    '''					&lt;xsl:text&gt; &lt;/xsl:text&gt;
    '''				&lt;/p&gt;
    '''
    '''		 [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property CookieCompliance() As String
        Get
            Return ResourceManager.GetString("CookieCompliance", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl &quot;/&gt;
    '''	
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CSSClassOverride&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Text&quot; /&gt;
    '''	&lt;xsl:param name=&quot;InjectDiv&quot; /&gt;
    '''	&lt;xsl:param name=&quot;UpdateTotalPriceDisplay&quot; /&gt;
    '''	
    '''&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''	&lt;di [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Deposit() As String
        Get
            Return ResourceManager.GetString("Deposit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl &quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl &quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Message&quot;/&gt;
    '''	&lt;xsl:param name=&quot;Duration&quot;/&gt;
    '''	&lt;xsl:param name=&quot;DepartureDate&quot;/&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot;/&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot;/&gt;
    '''	&lt;xsl:param name=&quot;TotalPax&quot;/&gt;
    '''	&lt;xsl:para [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property EmailBody() As String
        Get
            Return ResourceManager.GetString("EmailBody", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;BookingReference&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;input type=&quot;hidden&quot; id=&quot;hidEmailBookingReference&quot;/&gt;
    '''
    '''		&lt;div id=&quot;divSendDocumentationForm&quot; class=&quot;box primary&quot;&gt;
    '''
    '''			&lt;div class=&quot;boxTitle&quot;&gt;
    '''				&lt;h2 ml=&quot;Trade Bookings&quot;&gt;Email documents&lt;/h2&gt;
    '''			&lt;/div&gt;
    '''
    '''			&lt;p ml=&quot;Trade Bookings&quot;&gt;Please specify [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property EmailPopup() As String
        Get
            Return ResourceManager.GetString("EmailPopup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''	
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''    &lt;xsl:param name=&quot;CustomErrataType&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''        &lt;xsl:variable name=&quot;BasketErrataCount&quot; select=&quot;count(/BookingBasket/BasketErrata/Erratum)&quot; /&gt;
    '''        &lt;xsl:va [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Errata() As String
        Get
            Return ResourceManager.GetString("Errata", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divErrorHandler&quot; class=&quot;contentBox&quot;&gt;
    '''			&lt;div class=&quot;logo&quot;&gt;
    '''				&lt;xsl:text&gt; &lt;/xsl:text&gt;
    '''			&lt;/div&gt;
    '''			&lt;div ml=&quot;Error&quot;&gt;
    '''				An unexpected error has occurred.
    '''			&lt;/div&gt;
    '''			&lt;div&gt;
    '''				&lt;a href=&quot;/&quot; ml=&quot;Error&quot;&gt;Return to Homepage&lt;/a&gt;
    '''			&lt;/div&gt;
    '''		&lt;/div&gt;
    '''
    '''	&lt;/xsl:template&gt;
    '''&lt;/xsl:s [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property ErrorHandler() As String
        Get
            Return ResourceManager.GetString("ErrorHandler", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl &quot;/&gt;
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''	&lt;xsl:param name=&quot;DisplayType&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrentBasketExtraCode&quot; /&gt;
    '''	&lt;xsl:param name=&quot;JustResults&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Identifier&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ExtraCount&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Cur [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Extras() As String
        Get
            Return ResourceManager.GetString("Extras", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divFavouriteHotels&quot;&gt;
    '''
    '''			&lt;h2 ml=&quot;Favourite Hotels&quot;&gt;Favourite Hotels&lt;/h2&gt;
    '''
    '''			&lt;xsl:for-each select=&quot;FavouriteHotels/FavouriteHotel&quot;&gt;
    '''				&lt;a class=&quot;favouriteHotel&quot; href=&quot;{URL}&quot;&gt;
    '''					&lt;img src=&quot;{MainImage}&quot; alt=&quot;Hotel&quot;/&gt;
    '''
    '''					&lt;h3&gt;
    '''						&lt;xsl:value-of select=&quot;Name&quot;/&gt;
    '''				 [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property FavouriteHotels() As String
        Get
            Return ResourceManager.GetString("FavouriteHotels", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Reference&quot; /&gt;
    '''	&lt;xsl:param name=&quot;GuestName&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Booked&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Arrival&quot; /&gt;
    '''	&lt;xsl:param name=&quot;BookedStartDate&quot; /&gt;
    '''	&lt;xsl:param name=&quot;BookedEndDate&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ArrivalStartDate&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ArrivalEndDate&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CustomDateChange&quot; /&gt; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property FindBooking() As String
        Get
            Return ResourceManager.GetString("FindBooking", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Title&quot;/&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot;/&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot;/&gt;
    '''	&lt;xsl:param name=&quot;PriceFormat&quot;/&gt;
    '''	&lt;xsl:param name=&quot;BaggageQuantityError&quot;/&gt;
    '''	&lt;xsl:param name=&quot;ExtraQuantityError&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property FlightExtras() As String
        Get
            Return ResourceManager.GetString("FlightExtras", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CMSBaseURL&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;TotalPassengers&quot; /&gt;
    '''	&lt;xsl:param name=&quot;DisplayMode&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SelectButton [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property FlightResults() As String
        Get
            Return ResourceManager.GetString("FlightResults", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CMSBaseURL&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PerPersonPrices&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PaxCount&quot; /&gt;
    '''	&lt;xsl:param name=&quot;TimeOfDayControls&quot; /&gt;
    '''	&lt;xsl:param name=&quot;TimeSliders&quot; /&gt;
    '''	&lt;xs [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property FlightResultsFilter() As String
        Get
            Return ResourceManager.GetString("FlightResultsFilter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template name=&quot;FormatMoney&quot;&gt;
    '''		&lt;xsl:param name=&quot;Currency&quot;/&gt;
    '''		&lt;xsl:param name=&quot;Value&quot;/&gt;
    '''
    '''		&lt;xsl:variable name=&quot;Sign&quot;&gt;
    '''			&lt;xsl:if test=&quot;$Value &amp;lt; 0&quot;&gt;-&lt;/xsl:if&gt;
    '''		&lt;/xsl:variable&gt;
    '''
    '''		&lt;xsl:variable name=&quot;NewValue&quot;&gt;
    '''			&lt;xsl:choose&gt;
    '''				&lt;xsl:when test=&quot;$Value &amp;lt; 0&quot;&gt;
    '''					&lt;xsl:value-of select=&quot;$Value * -1&quot;/&gt;
    '''				&lt;/xsl:when&gt;
    '''		 [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Functions() As String
        Get
            Return ResourceManager.GetString("Functions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to -- Parameters
    '''declare @iCustomerID int
    '''
    '''-- Set Parameters
    '''
    '''set @iCustomerID = {0}
    '''
    '''-- Begin
    '''
    '''Select SUM(Amount)
    '''	from PointsTransaction
    '''	where CustomerID = @iCustomerID.
    '''</summary>
    Friend Shared ReadOnly Property GetCustomerPoints() As String
        Get
            Return ResourceManager.GetString("GetCustomerPoints", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;AdultYears&quot;/&gt;
    '''	&lt;xsl:param name=&quot;ChildYears&quot;/&gt;
    '''	&lt;xsl:param name=&quot;InfantYears&quot;/&gt;
    '''	&lt;xsl:param name=&quot;RequiresDOB&quot; select=&quot;&apos;true&apos;&quot;/&gt;
    '''	&lt;xsl:param name=&quot;ShowCopyLastName&quot; select=&quot;&apos;false&apos;&quot; /&gt;
    '''	&lt;xsl:param name=&quot;FirstDepartureDate&quot; /&gt;
    '''	&lt;xsl:param name=&quot;RequiresInfantDOB&quot; select=&quot;&apos;false&apos;&quot;/&gt;
    '''	&lt;xsl:param n [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property GuestDetails() As String
        Get
            Return ResourceManager.GetString("GuestDetails", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
    '''    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
    '''&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;PropertyReferenceID&quot;/&gt;
    '''	&lt;xsl:param name=&quot;MapMarkerPath&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''		&lt;xsl:for-each select=&quot;Property&quot;&gt;
    '''			&lt;div class=&quot;leftCont [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelContent() As String
        Get
            Return ResourceManager.GetString("HotelContent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl &quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl &quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divHotelDetails&quot;&gt;
    '''
    '''			
    '''			&lt;!-- Hotel main details --&gt;
    '''			&lt;div class=&quot;maindetails&quot;&gt;
    '''			 [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelDetails() As String
        Get
            Return ResourceManager.GetString("HotelDetails", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div class=&quot;overlay&quot;&gt;
    '''			&lt;xsl:text&gt; &lt;/xsl:text&gt;
    '''		&lt;/div&gt;
    '''
    '''		&lt;div class=&quot;popup&quot;&gt;
    '''			&lt;p id=&quot;pRoomRequestSuccess&quot; class=&quot;message success&quot; ml=&quot;Hotel Details&quot; style=&quot;display:none;&quot;&gt;Your reque [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelDetails_RequestRoomPopup() As String
        Get
            Return ResourceManager.GetString("HotelDetails_RequestRoomPopup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
    '''
    '''	&lt;xsl:param name=&quot;BaseURL&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Theme&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Message&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SenderName&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SellingCurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;RoomCount&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ResultsSummary&quot; /&gt;
    '''	&lt;xsl:param name=&quot;EmailLogoName&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;xsl:va [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelDetailsEmail() As String
        Get
            Return ResourceManager.GetString("HotelDetailsEmail", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	&lt;xsl:param name=&quot;PropertyReferenceID&quot; /&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl &quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl &quot;/&gt;
    '''
    '''
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''		&lt;!-- Email hotel --&gt;
    '''		&lt;div id=&quot;divHotelEmailDescription&quot;&gt;
    '''			&lt;h4 ml=&quot;Hotel Results&quot; &gt;Email description to...&lt;/h4&gt;
    '''			&lt;p id=&quot;pHotelEmailDescr [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelEmailDescription() As String
        Get
            Return ResourceManager.GetString("HotelEmailDescription", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''    &lt;xsl:if test=&quot;count(HotelListLinks/HotelListLink) &amp;gt; 0&quot;&gt;
    '''    
    '''		  &lt;div class=&quot;sidebarBox linklist&quot;&gt;
    '''
    '''			  &lt;div class=&quot;boxTitle&quot;&gt;
    '''				  &lt;h2&gt;
    '''					  &lt;trans ml=&quot;Hotel List Links&quot;&gt;Hotels in&lt;/trans&gt;
    '''					  &lt;xsl:text&gt; &lt;/xsl:text&gt;
    '''					  &lt;xsl:value-of select=&quot;HotelListLinks/Destin [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelListLinks() As String
        Get
            Return ResourceManager.GetString("HotelListLinks", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/Markdown.xsl&quot; /&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/Functions.xsl&quot; /&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PropertyReferenceID&quot; /&gt;
    '''	&lt;xsl:param name=&quot;MapMarkerPath&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PerPersonPrice&quot; /&gt;
    '''
    '''	&lt;xsl:template  [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelPopup() As String
        Get
            Return ResourceManager.GetString("HotelPopup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;xsl:for-each select=&quot;Property[1]&quot;&gt;
    '''
    '''			&lt;div id=&quot;divProperty_Images&quot; class=&quot;popupTrans&quot;&gt;
    '''
    '''				&lt;h3&gt;
    '''					&lt;xsl:value-of select=&quot;Region&quot; /&gt;
    '''					&lt;xsl:text&gt; - &lt;/xsl:text&gt;
    '''					&lt;xsl:value-of select=&quot;Resort&quot; /&gt;
    '''					&lt;xsl:text&gt; - &lt;/xsl:text&gt;
    '''					&lt;xsl:value-of select=&quot;Name&quot; /&gt;
    '''				&lt;/ [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelPopup_Images() As String
        Get
            Return ResourceManager.GetString("HotelPopup_Images", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''	
    '''&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''&lt;xsl:param name=&quot;TabbedContent&quot; /&gt;
    '''&lt;xsl:param name=&quot;SummaryLength&quot; /&gt;
    '''&lt;xsl:param name=&quot;RedirectURL&quot; /&gt;
    '''&lt;xsl:param name=&quot;PackagePrice&quot; /&gt;
    '''&lt; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelResults() As String
        Get
            Return ResourceManager.GetString("HotelResults", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
    '''    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
    '''&gt;
    '''    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CancellationChargesPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PropertyReferenceID&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Index&quot; /&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot;  /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot;  /&gt;
    '''	&lt;xsl:param name=&quot;DateToday&quot; /&gt;
    '''	&lt;xsl:param name [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelResults_CancellationCharges() As String
        Get
            Return ResourceManager.GetString("HotelResults_CancellationCharges", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
    '''    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
    '''&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CancellationChargesPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PropertyReferenceID&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Index&quot; /&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot;  /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot;  /&gt;
    '''	&lt;xsl:param name=&quot;DateToday&quot; /&gt;
    '''	&lt;xsl:param name=&quot;D [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelResults_Errata() As String
        Get
            Return ResourceManager.GetString("HotelResults_Errata", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div class=&quot;overlay&quot;&gt;
    '''			&lt;xsl:text&gt; &lt;/xsl:text&gt;
    '''		&lt;/div&gt;
    '''
    '''		&lt;div class=&quot;popup&quot;&gt;
    '''			&lt;p id=&quot;pRoomRequestSuccess&quot; class=&quot;message success&quot; ml=&quot;Hotel Results&quot; style=&quot;display:none;&quot;&gt;Your reque [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelResults_RequestRoomPopup() As String
        Get
            Return ResourceManager.GetString("HotelResults_RequestRoomPopup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	
    '''&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;	
    '''&lt;xsl:param name=&quot;PerPersonPrices&quot; /&gt;
    '''&lt;xsl:param name=&quot;ShowMapLink&quot; /&gt;
    '''&lt;xsl:param name=&quot;ScrollToTopAfterFilter&quot; /&gt;
    '''&lt;xsl:param name=&quot;ShowAverageScoreFilter&quot; /&gt;
    '''&lt;xsl:param name=&quot;MaxAver [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelResultsFilter() As String
        Get
            Return ResourceManager.GetString("HotelResultsFilter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''	
    '''&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''&lt;xsl:param name=&quot;PackagePrice&quot; /&gt;
    '''&lt;xsl:param name=&quot;PerPersonPrice&quot; /&gt;
    '''&lt;xsl:param name=&quot;PriceFormat&quot; /&gt;
    '''&lt;xsl:param name=&quot;HotelPriceOnly&quot; /&gt; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelResultsMapPopup() As String
        Get
            Return ResourceManager.GetString("HotelResultsMapPopup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;SearchMode&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Format&quot; /&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PriceFormat&quot; /&gt;
    '''	&lt;xsl:param name=&quot;FlightPrice&quot; /&gt;
    '''	&lt;xsl:param name=&quot;HotelsToDisplay&quot; /&gt;
    '''	&lt;xsl:param name=&quot;JustResults&quot; select=&quot;false&quot; /&gt;
    '''
    '''	&lt;xsl:pa [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelUpsell() As String
        Get
            Return ResourceManager.GetString("HotelUpsell", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Identifier&quot; /&gt;
    '''	&lt;xsl:param name=&quot;NavigationType&quot; /&gt;
    '''	&lt;xsl:param name=&quot;TransitionType&quot; select =&quot;&apos;slide&apos;&quot;/&gt;
    '''	&lt;xsl:param name=&quot;HoldTime&quot; select=&quot;2&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ImageWidth&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CMSBaseURL&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Overbranded&quot; /&gt;
    '''	
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;xsl:choose&gt; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property ImageRotator() As String
        Get
            Return ResourceManager.GetString("ImageRotator", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; omit-xml-declaration=&quot;yes&quot; indent=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;text&quot; /&gt;
    '''	&lt;xsl:param name=&quot;mode&quot; /&gt;
    '''
    '''
    '''	&lt;!-- Markdown --&gt;
    '''	&lt;xsl:template name=&quot;Markdown&quot;&gt;
    '''		&lt;xsl:param name=&quot;text&quot;/&gt;
    '''		&lt;xsl:param name=&quot;mode&quot;/&gt;
    '''
    '''		&lt;xsl:variable name=&quot;line&quot;&gt;
    '''			&lt;xsl:choose&gt;
    '''				&lt;xsl:when test=&quot;contains($text,&apos;&amp;#xA;&apos;)&quot;&gt;
    '''					&lt;xsl:value-of select=&quot;substring-before($text, &apos;&amp;# [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Markdown() As String
        Get
            Return ResourceManager.GetString("Markdown", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot;/&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot;/&gt;
    '''	&lt;xsl:param name=&quot;CMSBaseURL&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CSSClassOverride&quot; /&gt;
    '''	&lt;xsl:param name=&quot;SeatReservations&quot;/&gt;
    '''	&lt;xsl:param name=&quot;SeatReservationsChanged&quot;/&gt;
    '''	&lt;xsl:param name=&quot;LogoutRedirectURL&quot;/&gt;
    '''	&lt;xsl:param name=&quot;Theme&quot;/&gt;
    '''	&lt;xsl:para [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property MyBookings() As String
        Get
            Return ResourceManager.GetString("MyBookings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot; /&gt;
    '''
    '''	&lt;xsl:param name=&quot;LoginType&quot; /&gt;
    '''	&lt;xsl:param name=&quot;MMBURL&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CSSClassOverride&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ShowReminderLink&quot; /&gt;
    '''	&lt;xsl:param name=&quot;InsertWarningAfter&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divBookingLogin&quot; class=&quot;sidebarBox primary&quot;&gt;
    '''			&lt;xsl:if test=&quot;$CSSClassOverride != &apos;&apos;&quot;&gt;
    '''	 [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property MyBookingsLogin() As String
        Get
            Return ResourceManager.GetString("MyBookingsLogin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''	&lt;div id=&quot;divNavigationBar&quot;&gt;
    '''
    '''		&lt;ul&gt;
    '''			&lt;li class=&quot;title&quot;&gt;
    '''				&lt;xsl:value-of select=&quot;NavigationBar/NavigationBarTitle&quot;/&gt;
    '''			&lt;/li&gt;
    '''			&lt;xsl:for-each select=&quot;NavigationBar/MainMenu/MainMenuItem&quot;&gt;
    '''			&lt;li&gt;
    '''				&lt;!-- menu items --&gt;
    '''				&lt;a href=&quot;{URL}&quot;&gt;
    '''					&lt;xsl:value-of select=&quot;Name&quot;/&gt;
    ''' [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property NavigationBar() As String
        Get
            Return ResourceManager.GetString("NavigationBar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CSSClassOverride&quot; /&gt;
    '''	&lt;xsl:param name=&quot;InjectContainer&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ErrorStyle&quot; /&gt;
    '''	
    '''	
    '''	&lt;xsl:template match=&quot;/&quot;&gt;	
    '''			
    '''		&lt;div id=&quot;divNewsletter&quot;&gt;			
    '''			&lt;xsl:if test=&quot;$InjectContainer != &apos;&apos;&quot;&gt;
    '''				&lt;xsl:attribute name=&quot;style&quot;&gt;&lt;xsl:text&gt;display:none;&lt;/xsl:text&gt;&lt;/xsl:attribute&gt;
    '''			&lt;/xsl: [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Newsletter() As String
        Get
            Return ResourceManager.GetString("Newsletter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
    '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
    '''    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
    '''&gt;
    '''    &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
    '''
    '''    &lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div class=&quot;container&quot;&gt;
    '''
    '''			&lt;div class=&quot;sixteen columns&quot;&gt;
    '''
    '''				&lt;div class=&quot;box&quot;&gt;
    '''					&lt;h1&gt;Sorry - we haven&apos;t been able to find the page you are looking for.&lt;/h1&gt;
    '''					&lt;p&gt;You may have followed a broken or outdated link, o [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property PageNotFound() As String
        Get
            Return ResourceManager.GetString("PageNotFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;HTML&quot; /&gt;
    '''	
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;xsl:value-of select=&quot;$HTML&quot; disable-output-escaping=&quot;yes&quot;/&gt;
    '''		
    '''    &lt;/xsl:template&gt;
    '''&lt;/xsl:stylesheet&gt;
    '''.
    '''</summary>
    Friend Shared ReadOnly Property PaymentAuthorisation() As String
        Get
            Return ResourceManager.GetString("PaymentAuthorisation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href = &quot;../../xsl/Functions.xsl&quot; /&gt;
    '''	
    '''	&lt;xsl:param name=&quot;InfoParagraph&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;InjectTarget&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrentDiscount&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property PromoCode() As String
        Get
            Return ResourceManager.GetString("PromoCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''  &lt;xsl:if test=&quot;count(RelatedPages/RelatedPage) &amp;gt; 0&quot;&gt;
    '''    
    '''    &lt;div class=&quot;sidebarBox linklist&quot;&gt;
    '''
    '''      &lt;div class=&quot;boxTitle&quot;&gt;
    '''        &lt;h2&gt;
    '''          &lt;xsl:choose&gt;
    '''            &lt;xsl:when test=&quot;RelatedPages/RelatedPagesHeader != &apos;&apos;&quot;&gt;
    '''              &lt;xsl:value-of select=&quot;RelatedPages [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property RelatedPages() As String
        Get
            Return ResourceManager.GetString("RelatedPages", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Identifier&quot; /&gt;
    '''	&lt;xsl:param name=&quot;NavigationType&quot; /&gt;
    '''	&lt;xsl:param name=&quot;TransitionType&quot; select =&quot;&apos;slide&apos;&quot;/&gt;
    '''	&lt;xsl:param name=&quot;HoldTime&quot; select=&quot;2&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CMSBaseURL&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;xsl:variable name=&quot;ImageCount&quot; select=&quot;count(ImageRotator/Images/Image)&quot; /&gt;
    '''		&lt;x [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property ResponsiveImageRotator() As String
        Get
            Return ResourceManager.GetString("ResponsiveImageRotator", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;	
    '''	&lt;xsl:param name=&quot;Mode&quot; /&gt;	
    '''	&lt;xsl:param name=&quot;DaysEitherSide&quot; /&gt;
    '''	&lt;xsl:param name=&quot;DaysPerPage&quot; /&gt;
    '''	&lt;x [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property ResultsCarousel() As String
        Get
            Return ResourceManager.GetString("ResultsCarousel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divSeatSelections&quot;&gt;
    '''
    '''			&lt;xsl:for-each select=&quot;BookingBasket/BasketFlights/BasketFlight&quot;&gt;
    '''
    '''				&lt;xsl:if test=&quot;count(SeatMaps/SeatMap/Seats/Seat) &amp;gt; 0&quot;&gt;
    '''
    '''					&lt;div id=&quot;divSeatSelection&quot; cl [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property SeatSelection() As String
        Get
            Return ResourceManager.GetString("SeatSelection", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''
    '''
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ListClass&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ListItemClass&quot; /&gt;
    '''
    '''
    '''	&lt;xsl:template match=&quot;/BasketCarHire&quot;&gt;
    '''
    '''		&lt;xsl:for-each select=&quot;CarHire&quot;&gt;
    '''			&lt;h3&gt;Your selected car hire&lt;/h3&gt; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property SelectedCarHire() As String
        Get
            Return ResourceManager.GetString("SelectedCarHire", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;script type=&quot;text/javascript&quot;&gt;
    '''			int.ll.OnLoad.Run(function () { SessionPersister.Persist(); });
    '''		&lt;/script&gt;
    '''
    '''
    '''	&lt;/xsl:template&gt;
    '''
    '''&lt;/xsl:stylesheet&gt;
    '''.
    '''</summary>
    Friend Shared ReadOnly Property SessionPersister() As String
        Get
            Return ResourceManager.GetString("SessionPersister", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divSimilarHotels&quot;&gt;
    '''			
    '''				&lt;h2 ml=&quot;Similar Hotels&quot;&gt;Similar Hotels&lt;/h2&gt;
    '''
    '''				&lt;xsl:for-each select=&quot;SimilarHotels/SimilarHotel&quot;&gt;
    '''					&lt;a class=&quot;similarHotel&quot; href=&quot;{URL}&quot;&gt;
    '''						&lt;img src=&quot;{MainImage}&quot; alt=&quot;Hotel&quot;/&gt;
    '''
    '''						&lt;h3&gt;&lt;xsl:value-of select=&quot;Name&quot;/&gt;&lt;/h3&gt;
    '''						&lt;p cl [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property SimilarHotels() As String
        Get
            Return ResourceManager.GetString("SimilarHotels", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;		
    '''
    '''			&lt;xsl:for-each select=&quot;Sitemap&quot;&gt;
    '''
    '''				&lt;div id=&quot;divSitemap&quot;&gt;
    '''
    '''					&lt;xsl:if test=&quot;Header != &apos;&apos;&quot;&gt;
    '''						&lt;h1&gt;
    '''							&lt;xsl:value-of select=&quot;Header&quot;/&gt;
    '''						&lt;/h1&gt;
    '''					&lt;/xsl:if&gt;
    '''
    '''					&lt;xsl:for-each select=&quot;Groups/Group&quot;&gt;
    '''						&lt;div class=&quot;group clear&quot;&gt;
    '''
    '''							&lt;!--Title--&gt;
    '''				 [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Sitemap() As String
        Get
            Return ResourceManager.GetString("Sitemap", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''&lt;xsl:param name=&quot;DocumentPath&quot; /&gt;
    '''&lt;xsl:param name=&quot;IAgreeText&quot; /&gt;
    '''&lt;xsl:param name=&quot;CSSClassOverride&quot; /&gt;
    '''	
    '''&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''	&lt;div id=&quot;divTermsAndConditions&quot;&gt;
    '''
    '''    &lt;xsl:attribute name =&quot;class&quot;&gt;
    '''      &lt;xsl:choose&gt;
    '''        &lt;xsl:when test=&quot;$CSSClassOverride != &apos;&apos;&quot;&gt;
    '''          &lt;xsl:value-of select=&quot;$CSSCla [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property TermsAndConditions() As String
        Get
            Return ResourceManager.GetString("TermsAndConditions", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''	&lt;xsl:param name=&quot;Confirmation&quot; select=&quot;&apos;false&apos;&quot; /&gt;
    '''	
    '''	&lt;xsl:template match=&quot;/&quot;&gt;		
    '''		
    '''		&lt;xsl:for-each select=&quot;TrackingAffiliates/TrackingAffiliate&quot;&gt;
    '''			
    '''			&lt;xsl:choose&gt;
    '''				&lt;xsl:when test=&quot;$Confirmation = &apos;true&apos; and ConfirmationScript != &apos;&apos;&quot;&gt;
    '''					&lt;xsl:value-of select=&quot;ConfirmationScript&quot; disable-output-escapi [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property TrackingAffiliate() As String
        Get
            Return ResourceManager.GetString("TrackingAffiliate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''	&lt;xsl:param name=&quot;SellingCurrencyExchange&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CreditCardAgent&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Update&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;xsl:choose&gt;
    '''			&lt;xsl:when test=&quot;$Update = &apos;True&apos;&quot;&gt;
    '''				&lt;xsl:call-template name=&quot;Boo [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property TradeBookings() As String
        Get
            Return ResourceManager.GetString("TradeBookings", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;LoginType&quot; /&gt;
    '''	&lt;xsl:param name=&quot;LoginMethod&quot; /&gt;
    '''	&lt;xsl:param name=&quot;RedirectURL&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Email&quot; /&gt;
    '''	&lt;xsl:param name=&quot;HideHeader&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Placeholders&quot; /&gt;
    '''	&lt;xsl:param name=&quot;DrawRememberMe&quot; /&gt;
    '''	&lt;xsl:param name=&quot;UseLoginType&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;d [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property TradeLogin() As String
        Get
            Return ResourceManager.GetString("TradeLogin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divTradeReference&quot; class=&quot;trade-reference box primary&quot;&gt;
    '''
    '''			&lt;div class=&quot;boxTitle&quot;&gt;
    '''				&lt;h2&gt;
    '''					&lt;trans ml=&quot;Trade Reference&quot;&gt;Your Reference&lt;/trans&gt;
    '''					&lt;span ml=&quot;Trade Reference&quot;&gt;*&lt;/span&gt;
    '''				&lt;/h2&gt;
    '''			&lt;/div&gt;
    '''
    '''			&lt;input type=&quot;text&quot; name=&quot;txtTradeReference&quot; id=&quot;txtTrad [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property TradeReference() As String
        Get
            Return ResourceManager.GetString("TradeReference", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''  &lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''  &lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot; /&gt;
    '''
    '''    &lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''      &lt;xsl:if test=&quot;TransferInformationReturn/Response/VehicleDetails != &apos;&apos;&quot;&gt;
    '''        &lt;h5 ml=&quot;Transfers&quot;&gt;
    '''          &lt;xsl:text&gt;Vehicle Details&lt;/xsl:text&gt;
    '''        &lt;/h5&gt;
    '''        &lt;xsl:ca [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property TransferInformationPopup() As String
        Get
            Return ResourceManager.GetString("TransferInformationPopup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''	
    '''&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''	
    '''&lt;xsl:param name=&quot;Theme&quot;/&gt;
    '''&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''&lt;xsl:param name=&quot;SearchMode&quot; /&gt;
    '''&lt;xsl:param name=&quot;ShowFlightCodeFields&quot; /&gt;
    '''&lt;xsl:param name=&quot;RequiresPhoneNumber&quot; /&gt;
    '''&lt;xsl:param nam [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property Transfers() As String
        Get
            Return ResourceManager.GetString("Transfers", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/markdown.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div class=&quot;sidebarBox linklist&quot;&gt;
    '''
    '''			&lt;div class=&quot;boxTitle&quot;&gt;
    '''				&lt;h2 ml=&quot;Useful Links&quot;&gt;Useful Links&lt;/h2&gt;
    '''			&lt;/div&gt;
    '''
    '''			&lt;xsl:call-template name=&quot;Markdown&quot;&gt;
    '''				&lt;xsl:with-param name=&quot;text&quot; select=&quot;UsefulLinks&quot;/&gt;
    '''			&lt;/xsl:call-templ [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property UsefulLinks() As String
        Get
            Return ResourceManager.GetString("UsefulLinks", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Type&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Theme&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Website&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Hidden&quot; select=&quot;&apos;False&apos;&quot; /&gt;
    '''    &lt;xsl:param name=&quot;RemoveProtocall&quot; select=&quot;&apos;True&apos;&quot; /&gt;
    '''	
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divWaitMessage&quot;&gt;
    '''			
    '''			&lt;xsl:if test=&quot;$Hidden = &apos;True&apos;&quot;&gt;
    '''				&lt;xsl:attribute name [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property WaitMessage() As String
        Get
            Return ResourceManager.GetString("WaitMessage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Type&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Theme&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Website&quot; /&gt;
    '''	&lt;xsl:param name=&quot;Hidden&quot; select=&quot;&apos;False&apos;&quot; /&gt;
    '''    &lt;xsl:param name=&quot;RemoveProtocall&quot; select=&quot;&apos;True&apos;&quot; /&gt;
    '''	
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''		
    '''		
    '''		&lt;xsl:if test=&quot;WaitMessages/WaitMessage[Type=$Type]/TimeoutText and WaitMessages/WaitMe [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property WaitMessageTimeout() As String
        Get
            Return ResourceManager.GetString("WaitMessageTimeout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:include href=&quot;../../xsl/functions.xsl&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Title&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbol&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CurrencySymbolPosition&quot; /&gt;
    '''	&lt;xsl:param name=&quot;PriceFormat&quot; /&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divBaggage&quot; class=&quot;box primary&quot;&gt;
    '''
    '''			&lt;input type=&quot;hidden&quot; id=&quot;hidBaggagePax&quot;  [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property ZeroPriceBaggage() As String
        Get
            Return ResourceManager.GetString("ZeroPriceBaggage", resourceCulture)
        End Get
    End Property
End Class
