'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MapControl

	'''<summary>
	'''divMapHolder control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divMapHolder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''h2Title control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents h2Title As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hidMapIcons control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidMapIcons As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidMapTheme control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidMapTheme As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidMapPoints control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidMapPoints As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidPopupX control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidPopupX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidPopupY control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidPopupY As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidClusterPopupX control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidClusterPopupX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidClusterPopupY control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidClusterPopupY As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
