export const EMAILFORM_UPDATED = 'EMAILFORM_UPDATED';
export const EMAILFORM_RESET = 'EMAILFORM_RESET';
export const FORM_ADD_WARNING = 'FORM_ADD_WARNING';
export const FORM_RESET_WARNINGS = 'FORM_RESET_WARNINGS';
export const FORM_INITIALIZE = 'FORM_INITIALIZE';
export const FORM_SUBMITTED = 'FORM_SUBMITTED';
export const FORM_TOGGLE_PASSWORD = 'FORM_TOGGLE_PASSWORD';
export const FORM_SET_MESSAGE = 'FORM_SET_MESSAGE';
export const FORM_RESET_MESSAGE = 'FORM_RESET_MESSAGE';

export const MMB_LOAD_BOOKINGS_REQUEST = 'MMB_LOAD_BOOKINGS_REQUEST';
export const MMB_LOAD_BOOKINGS_SUCCESS = 'MMB_LOAD_BOOKINGS_SUCCESS';
export const MMB_SORT_BOOKINGS = 'MMB_SORT_BOOKINGS';
export const MMB_UPDATE_PAGE = 'MMB_UPDATE_PAGE';
export const MMB_UPDATE_RESULTS_PER_PAGE = 'MMB_UPDATE_RESULTS_PER_PAGE';
export const MMB_FILTER_BOOKINGS = 'MMB_FILTER_BOOKINGS';
export const MMB_RESET_FILTERS = 'MMB_RESET_FILTERS';
export const MMB_UPDATE_CANCELLATION_BOOKING = 'MMB_UPDATE_CANCELLATION_BOOKING';
export const MMB_UPDATE_CANCELLATION_COMPONENTS = 'MMB_UPDATE_CANCELLATION_COMPONENTS';
export const MMB_UPDATE_CANCELLATION_INFORMATION = 'MMB_UPDATE_CANCELLATION_INFORMATION';
export const MMB_CANCEL_BOOKING = 'MMB_CANCEL_BOOKING';
export const MMB_CLEAR_CANCELLATION_STATUS = 'MMB_CLEAR_CANCELLATION_STATUS';
export const MMB_DOCUMENTATION_WARNING = 'MMB_DOCUMENTATION_WARNING';

export const DIRECT_DEBIT_LOAD_REQUEST = 'DIRECT_DEBIT_LOAD_REQUEST';
export const DIRECT_DEBIT_LOAD_SUCCESS = 'DIRECT_DEBIT_LOAD_SUCCESS';

export const QUOTE_SEARCH_REQUEST = 'QUOTE_SEARCH_REQUEST';
export const QUOTE_SEARCH_RESULT = 'QUOTE_SEARCH_RESULT';
export const QUOTE_FILTER_UPDATED = 'QUOTE_FILTER_UPDATED';
export const QUOTE_RESULTS_UPDATED = 'QUOTE_RESULTS_UPDATED';
export const QUOTE_FILTER_RESET = 'QUOTE_FILTER_RESET';
