'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class res
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iVectorWidgets.res", GetType(res).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divHotelDetails&quot;&gt;
    '''
    '''			&lt;div&gt;
    '''				&lt;h1&gt;Hotel Name&lt;/h1&gt;
    '''				&lt;h3&gt;Geographical Information&lt;/h3&gt;
    '''			&lt;/div&gt;
    '''
    '''			&lt;div&gt;
    '''				
    '''				&lt;!-- Main Image --&gt;
    '''				&lt;img id=&quot;imgMainImage&quot; src=&quot;/Themes/GoSyden/Images/call-center.jpg&quot; alt=&quot;Test&quot;/&gt;
    '''
    '''				&lt;!-- Other images --&gt;
    '''
    '''				&lt;div id=&quot; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property HotelDetails() As String
        Get
            Return ResourceManager.GetString("HotelDetails", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:param name=&quot;Identifier&quot; /&gt;
    '''	&lt;xsl:param name=&quot;NavigationType&quot; /&gt;
    '''	&lt;xsl:param name=&quot;TransitionType&quot; /&gt;
    '''	&lt;xsl:param name=&quot;TransitionTime&quot; /&gt;
    '''	&lt;xsl:param name=&quot;ImageWidth&quot; /&gt;
    '''	&lt;xsl:param name=&quot;CMSBaseURL&quot; /&gt;
    '''	
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;xsl:variable name=&quot;ImageCount&quot; select=&quot;count(ImageRotator/Images/Ima [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property ImageRotator() As String
        Get
            Return ResourceManager.GetString("ImageRotator", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''	&lt;div id=&quot;divNavigationBar&quot;&gt;
    '''
    '''		&lt;ul&gt;
    '''			&lt;li class=&quot;title&quot;&gt;
    '''				&lt;xsl:value-of select=&quot;NavigationBar/NavigationBarTitle&quot;/&gt;
    '''			&lt;/li&gt;
    '''			&lt;xsl:for-each select=&quot;NavigationBar/MainMenu/MainMenuItem&quot;&gt;
    '''			&lt;li&gt;
    '''				&lt;a href=&quot;{URL}&quot;&gt;
    '''					&lt;xsl:value-of select=&quot;Name&quot;/&gt;
    '''				&lt;/a&gt;
    '''				&lt;ul class=&quot; [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property NavigationBar() As String
        Get
            Return ResourceManager.GetString("NavigationBar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
    '''&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot;&gt;
    '''	&lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot; omit-xml-declaration=&quot;yes&quot;/&gt;
    '''
    '''	&lt;xsl:template match=&quot;/&quot;&gt;
    '''
    '''		&lt;div id=&quot;divSimilarHotels&quot;&gt;
    '''			
    '''				&lt;h2&gt;Similar Hotels&lt;/h2&gt;
    '''
    '''				&lt;h3&gt;
    '''					&lt;xsl:value-of select=&quot;SimilarHotels/SimilarHotel/Region&quot;/&gt;
    '''				&lt;/h3&gt;
    '''
    '''				&lt;xsl:for-each select=&quot;SimilarHotels/SimilarHotel&quot;&gt;
    '''					&lt;div class=&quot;similarHotel&quot;&gt;
    '''						&lt;div class=&quot;left&quot;&gt;
    '''							&lt;a href=&quot;/hot [rest of string was truncated]&quot;;.
    '''</summary>
    Friend Shared ReadOnly Property SimilarHotels() As String
        Get
            Return ResourceManager.GetString("SimilarHotels", resourceCulture)
        End Get
    End Property
End Class
