//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intuitive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreAbstractionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreAbstractionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intuitive.CoreAbstractionsResources", typeof(CoreAbstractionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic dependency: &apos;{0}!&apos; The key &apos;{1}&apos; is already been referenced in ths graph..
        /// </summary>
        public static string CyclicDependencyExceptionMessage {
            get {
                return ResourceManager.GetString("CyclicDependencyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null or an empty string..
        /// </summary>
        public static string IsNotNullOrEmptyExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotNullOrEmptyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null or an empty set..
        /// </summary>
        public static string IsNotNullOrEmptySetExceptionMessage {
            get {
                return ResourceManager.GetString("IsNotNullOrEmptySetExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing dependency: &apos;{0}?. The key &apos;{1}&apos; cannot be found in the graph&apos;..
        /// </summary>
        public static string MissingDependencyExceptionMessage {
            get {
                return ResourceManager.GetString("MissingDependencyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module id value must be provided..
        /// </summary>
        public static string ModuleIdRequiredExceptionMessage {
            get {
                return ResourceManager.GetString("ModuleIdRequiredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation could not be performed because the instance is already disposed. This usually happens if you attempt to use a disposed instance after a call to its Dispose() method, or outstide of the using statement in which it is scoped..
        /// </summary>
        public static string ObjectDisposedExceptionMessage {
            get {
                return ResourceManager.GetString("ObjectDisposedExceptionMessage", resourceCulture);
            }
        }
    }
}
