'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HotelRequestsControl

	'''<summary>
	'''divHotelRequests control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divHotelRequests As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hHotelRequests_Title control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hHotelRequests_Title As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''pHotelRequests_Text control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pHotelRequests_Text As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divArrivalTime control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divArrivalTime As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddlArrivalTime control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlArrivalTime As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''txtHotelRequests_Requests control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtHotelRequests_Requests As Global.System.Web.UI.HtmlControls.HtmlTextArea
End Class
