'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SearchToolUserControl
    
    '''<summary>
    '''divSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hidInsertWarningAfter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInsertWarningAfter As Global.Intuitive.WebControls.Hidden
    
    '''<summary>
    '''hidDefaultSearchValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDefaultSearchValues As Global.Intuitive.WebControls.Hidden
    
    '''<summary>
    '''hidDatepickerCultureCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDatepickerCultureCode As Global.Intuitive.WebControls.Hidden
    
    '''<summary>
    '''divSearchTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSearchTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''h2_SearchTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents h2_SearchTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divSearchMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSearchMode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ulSearchMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulSearchMode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hidSearchMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSearchMode As Global.Intuitive.WebControls.Hidden
    
    '''<summary>
    '''hidFlightPlusHotelURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidFlightPlusHotelURL As Global.Intuitive.WebControls.Hidden
    
    '''<summary>
    '''hidUseFlightCarouselResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidUseFlightCarouselResults As Global.Intuitive.WebControls.Hidden
    
    '''<summary>
    '''lblDepartureLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepartureLocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divDepartingFromCountryCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDepartingFromCountryCountry As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlDepartingFromCountryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartingFromCountryID As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''divDepartingFromDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDepartingFromDropdown As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlDepartingFromID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartingFromID As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''divDepartingFromAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDepartingFromAuto As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''acpDepartingFromID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpDepartingFromID As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''acpDepartingFromIDHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpDepartingFromIDHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''acpDepartingFromIDScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpDepartingFromIDScript As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''divShowHideDepartingFromAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divShowHideDepartingFromAutoComplete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''aShowDepartingFromDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowDepartingFromDropdown As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aShowDepartingFromAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowDepartingFromAutoComplete As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''hidAirportDepartingFromID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAirportDepartingFromID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDestination As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divArrivingAtDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArrivingAtDestination As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divArrivingAtCountryCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArrivingAtCountryCountry As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlCountryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCountryID As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''divArrivingAtDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArrivingAtDropdown As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlRegionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegionID As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''divArrivingAtAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArrivingAtAuto As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''acpArrivingAtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpArrivingAtID As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''acpArrivingAtIDHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpArrivingAtIDHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''acpArrivingAtIDScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpArrivingAtIDScript As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''divShowHideArrivingAtAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divShowHideArrivingAtAutoComplete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''aShowArrivingAtDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowArrivingAtDropdown As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aShowArrivingAtAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowArrivingAtAutoComplete As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''divArrivingAtAirport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArrivingAtAirport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlArrivalAirportID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlArrivalAirportID As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''divArrivingAtAirportAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divArrivingAtAirportAuto As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''acpArrivingAtAirportID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpArrivingAtAirportID As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''acpArrivingAtAirportIDHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpArrivingAtAirportIDHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''acpArrivingAtAirportIDScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpArrivingAtAirportIDScript As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''divShowHideAirportArrivingAtAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divShowHideAirportArrivingAtAutoComplete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''aShowAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowAutoComplete As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aHideAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aHideAutoComplete As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''hidArrivingAtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidArrivingAtID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''fldPriorityProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fldPriorityProperty As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProperty As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''acpPriorityPropertyID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpPriorityPropertyID As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''acpPriorityPropertyIDHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpPriorityPropertyIDHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblDepartureDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepartureDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dlReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlReturn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblReturnDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReturnDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDuration As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDuration As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''hidDurationSingularSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDurationSingularSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidDurationPluralSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDurationPluralSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidDatepickerMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDatepickerMonths As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidDatepickerFirstDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDatepickerFirstDay As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidShowDatePickerDropDowns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidShowDatePickerDropDowns As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidReturnDatepicker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidReturnDatepicker As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidDaysAhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidDaysAhead As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidReturnMinDaysAhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidReturnMinDaysAhead As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRooms As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRooms As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''hidRoomsSingularSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidRoomsSingularSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidRoomsPluralSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidRoomsPluralSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblPickupLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPickupLocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlPickupType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPickupType As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''acpPropertyIDTransferPickup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpPropertyIDTransferPickup As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''acpPropertyIDTransferPickupHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpPropertyIDTransferPickupHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''acpAirportIDTransferPickup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpAirportIDTransferPickup As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''acpAirportIDTransferPickupHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpAirportIDTransferPickupHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''divAirportDropdownTransferPickup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAirportDropdownTransferPickup As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlAirportTransferPickup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAirportTransferPickup As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''divShowHideTransferDepartingFromAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divShowHideTransferDepartingFromAutoComplete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''aShowTransferDepartingFromDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowTransferDepartingFromDropDown As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aShowTransferDepartingFromAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowTransferDepartingFromAutoComplete As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''hidTransferPickupLocationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidTransferPickupLocationID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblDropOffLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDropOffLocation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlDropOffType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDropOffType As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''acpPropertyIDTransferDropOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpPropertyIDTransferDropOff As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''acpPropertyIDTransferDropOffHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpPropertyIDTransferDropOffHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''acpAirportIDTransferDropOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpAirportIDTransferDropOff As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''acpAirportIDTransferDropOffHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpAirportIDTransferDropOffHidden As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''divAirportDropdownTransferDropOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAirportDropdownTransferDropOff As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlAirportTransferDropoff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAirportTransferDropoff As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''divShowHideTransferArrivingAtAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divShowHideTransferArrivingAtAutoComplete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''aShowTransferArrivingAtDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowTransferArrivingAtDropDown As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aShowTransferArrivingAtAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowTransferArrivingAtAutoComplete As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''hidTransferDropOffLocationID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidTransferDropOffLocationID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidReturnTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidReturnTransfer As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblPickupDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPickupDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblArrivalTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArrivalTime As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblDropOffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDropOffDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblDropOffTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDropOffTime As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblPassengers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPassengers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblAdults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdults As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblChildren control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChildren As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblInfants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfants As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tdRoom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdRoom1 As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''ddlAdults_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAdults_1 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildren_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildren_1 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlInfants_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInfants_1 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_1_1 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_1_2 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_1_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_1_3 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_1_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_1_4 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlAdults_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAdults_2 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildren_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildren_2 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlInfants_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInfants_2 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_2_1 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_2_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_2_2 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_2_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_2_3 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_2_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_2_4 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlAdults_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAdults_3 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildren_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildren_3 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlInfants_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInfants_3 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_3_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_3_1 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_3_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_3_2 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_3_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_3_3 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''ddlChildAge_3_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChildAge_3_4 As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''hidAdultsSingularSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAdultsSingularSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidAdultsPluralSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAdultsPluralSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidChildrenSingularSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidChildrenSingularSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidChildrenPluralSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidChildrenPluralSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidInfantsSingularSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInfantsSingularSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidInfantsPluralSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidInfantsPluralSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidAgeSingularSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAgeSingularSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidAgePluralSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidAgePluralSuffix As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''divSearch_Advanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSearch_Advanced As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlMealBasisID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMealBasisID As Global.Intuitive.Web.Controls.Dropdown
    
    '''<summary>
    '''hidRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidRating As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidPropertyReferenceID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidPropertyReferenceID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''aShowAdvancedOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aShowAdvancedOptions As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''aHideAdvancedOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aHideAdvancedOptions As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHide As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''hidSingleRoomLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSingleRoomLabel As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidMultiRoomLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidMultiRoomLabel As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidWarning_Invalid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidWarning_Invalid As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidWarning_NoResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidWarning_NoResults As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidStartMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidStartMode As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidExpandAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidExpandAction As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidUseShortDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidUseShortDates As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidSearchRedirects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidSearchRedirects As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''lblHighRatedHotelFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHighRatedHotelFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spnHighRatedHotelFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnHighRatedHotelFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divSearchAgain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSearchAgain As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnSearchAgain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchAgain As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''plcPreSearchScript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plcPreSearchScript As Global.Intuitive.WebControls.PlaceHolder
End Class
