'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentControl

	'''<summary>
	'''divPaymentDetails_Options control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divPaymentDetails_Options As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hPaymentOption_Title control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hPaymentOption_Title As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divBillingAddress control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divBillingAddress As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''h1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents h1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hidUseBillingAddress control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidUseBillingAddress As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''ddlBillingAddress_Title control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlBillingAddress_Title As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlBillingAddress_BookingCountry control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlBillingAddress_BookingCountry As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''divPaymentDetails control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divPaymentDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hPayment_Title control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hPayment_Title As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hidDisablePriceUpdate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidDisablePriceUpdate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''pPayment_Text control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pPayment_Text As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddlCCCardTypeID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCCardTypeID As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlCCStartMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCStartMonth As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''ddlCCStartYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCStartYear As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''ddlCCExpireMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCExpireMonth As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''ddlCCExpireYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCExpireYear As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''aPayment_CSVTooltip control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents aPayment_CSVTooltip As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''dtIssueNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtIssueNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddIsueNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddIsueNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hidSurcharge control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidSurcharge As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidTotalAmount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidTotalAmount As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidCurrencySymbol control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCurrencySymbol As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidPerformValidation control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidPerformValidation As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
