export const AIRPORTS_REQUEST = 'AIRPORTS_REQUEST';
export const AIRPORTS_LOAD_SUCCESS = 'AIRPORTS_LOAD_SUCCESS';
export const AIRPORTS_LOAD_ERROR = 'AIRPORTS_LOAD_ERROR';

export const AIRPORT_GROUPS_REQUEST = 'AIRPORT_GROUPS_REQUEST';
export const AIRPORT_GROUPS_LOAD_SUCCESS = 'AIRPORT_GROUPS_LOAD_SUCCESS';

export const AIRPORT_RESORT_GROUPS_REQUEST = 'AIRPORT_RESORT_GROUPS_REQUEST';
export const AIRPORT_RESORT_GROUPS_LOAD_SUCCESS = 'AIRPORT_RESORT_GROUPS_LOAD_SUCCESS';

export const BOOKINGCOUNTRIES_REQUEST = 'BOOKINGCOUNTRIES_REQUEST';
export const BOOKINGCOUNTRIES_LOAD_SUCCESS = 'BOOKINGCOUNTRIES_LOAD_SUCCESS';

export const BRANDS_REQUEST = 'BRANDS_REQUEST';
export const BRANDS_LOAD_SUCCESS = 'BRANDS_LOAD_SUCCESS';

export const CARDTYPES_REQUEST = 'CARDTYPES_REQUEST';
export const CARDTYPES_LOAD_SUCCESS = 'CARDTYPES_LOAD_SUCCESS';

export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST';
export const COUNTRIES_LOAD_SUCCESS = 'COUNTRIES_LOAD_SUCCESS';
export const COUNTRIES_LOAD_ERROR = 'COUNTRIES_LOAD_ERROR';

export const DEALFINDERFLIGHTCACHEROUTE_LOAD_DATES_REQUEST = 'DFFLIGHTCACHE_LOAD_DATES_REQUEST';
export const DEALFINDERFLIGHTCACHEROUTE_LOAD_DATES_SUCCESS = 'DFFLIGHTCACHE_LOAD_DATES_SUCCESS';
export const DEALFINDERFLIGHTCACHEROUTE_CLEAR = 'DEALFINDERFLIGHTCACHEROUTE_CLEAR';
export const DEALFINDERFLIGHTCACHEROUTE_INITIALISE = 'DEALFINDERFLIGHTCACHEROUTE_INITIALISE';

export const FILTERFACILITIES_REQUEST = 'FILTERFACILITIES_REQUEST';
export const FILTERFACILITIES_LOAD_SUCCESS = 'FILTERFACILITIES_LOAD_SUCCESS';

export const FLIGHTCACHEROUTE_LOAD_DATES_REQUEST = 'FLIGHTCACHEROUTE_LOAD_DATES_REQUEST';
export const FLIGHTCACHEROUTE_LOAD_DATES_SUCCESS = 'FLIGHTCACHEROUTE_LOAD_DATES_SUCCESS';
export const FLIGHTCACHEROUTE_CLEAR = 'FLIGHTCACHEROUTE_CLEAR';
export const FLIGHTCACHEROUTE_INITIALISE = 'FLIGHTCACHEROUTE_INITIALISE';

export const FLIGHTCARRIERS_REQUEST = 'FLIGHTCARRIERS_REQUEST';
export const FLIGHTCARRIERS_LOAD_SUCCESS = 'FLIGHTCARRIERS_LOAD_SUCCESS';

export const FLIGHTCLASSES_REQUEST = 'FLIGHTCLASSES_REQUEST';
export const FLIGHTCLASSES_LOAD_SUCCESS = 'FLIGHTCLASSES_LOAD_SUCCESS';

export const MEALBASIS_REQUEST = 'MEALBASIS_REQUEST';
export const MEALBASIS_LOAD_SUCCESS = 'MEALBASIS_LOAD_SUCCESS';

export const PRODUCTATTRIBUTES_REQUEST = 'PRODUCTATTRIBUTES_REQUEST';
export const PRODUCTATTRIBUTES_LOAD_SUCCESS = 'PRODUCTATTRIBUTES_LOAD_SUCCESS';

export const ROUTEAVAILABILITY_LOAD_SUCCESS = 'ROUTEAVAILABILITY_LOAD_SUCCESS';
