export const SEARCHDETAILS_LOAD_SUCCESS = 'SEARCHDETAILS_LOAD_SUCCESS';
export const SEARCH_UPDATE_VALUE = 'SEARCH_UPDATE_VALUE';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RESULT = 'SEARCH_RESULT';

export const SEARCHRESULTS_REQUEST = 'SEARCHRESULTS_REQUEST';
export const SEARCHRESULTS_LOAD_SUCCESS = 'SEARCHRESULTS_LOAD_SUCCESS';
export const SEARCHRESULTS_FILTER_UPDATE = 'SEARCHRESULTS_FILTER_UPDATE';
export const SEARCHRESULTS_SORT = 'SEARCHRESULTS_SORT';
export const SEARCHRESULTS_UPDATED = 'SEARCHRESULTS_UPDATED';
export const SEARCHRESULTS_UPDATE_PAGE = 'SEARCHRESULTS_UPDATE_PAGE';
export const SEARCHRESULTS_CHANGE_FLIGHT = 'SEARCHRESULTS_CHANGE_FLIGHT';

export const BASKET_BOOK_REQUEST = 'BASKET_BOOK_REQUEST';
export const BASKET_BOOK_SUCCESS = 'BASKET_BOOK_SUCCESS';
export const BASKET_BOOK_ERROR = 'BASKET_BOOK_ERROR';
export const BASKET_LOAD_REQUEST = 'BASKET_LOAD_REQUEST';
export const BASKET_LOAD_SUCCESS = 'BASKET_LOAD_SUCCESS';
export const BASKET_PREBOOK_REQUEST = 'BASKET_PREBOOK_REQUEST';
export const BASKET_PREBOOK_ERROR = 'BASKET_PREBOOK_ERROR';
export const BASKET_PREBOOK_SUCCESS = 'BASKET_PREBOOK_SUCCESS';
export const BASKET_REMOVE_PROMOCODE = 'BASKET_REMOVE_PROMOCODE';
export const BASKET_UPDATE_CANCELLATION = 'BASKET_UPDATE_CANCELLATION';
export const BASKET_UPDATE_ERRATA = 'BASKET_UPDATE_ERRATA';
export const BASKET_UPDATE_PROMOCODE = 'BASKET_UPDATE_PROMOCODE';
export const BASKET_UPDATE_WORKING_PROMOCODE = 'BASKET_UPDATE_WORKING_PROMOCODE';
export const BASKET_UPDATE_REFERENCE_REQUIREMENT = 'BASKET_UPDATE_REFERENCE_REQUIREMENT';
export const BASKET_UPDATE_REQUEST = 'BASKET_UPDATE_REQUEST';
export const BASKET_UPDATE_VALUE = 'BASKET_UPDATE_VALUE';
export const BASKET_UPDATE_STATE_VALUE = 'BASKET_UPDATE_STATE_VALUE';
export const BASKET_UPDATE_SUCCESS = 'BASKET_UPDATE_SUCCESS';
export const BASKET_UPDATE_TERMS = 'BASKET_UPDATE_TERMS';
export const BASKET_ADD_WARNING = 'BASKET_ADD_WARNING';
export const BASKET_RESET_WARNINGS = 'BASKET_RESET_WARNINGS';

export const SITE_REQUEST = 'SITE_REQUEST';
export const SITE_LOAD_SUCCESS = 'SITE_LOAD_SUCCESS';

export const CMS_WEBSITE_REQUEST = 'CMS_WEBSITE_REQUEST';
export const CMS_WEBSITE_LOAD_SUCCESS = 'CMS_WEBSITE_LOAD_SUCCESS';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

export const ALERT_ADD = 'ALERT_ADD';
export const ALERT_REMOVE = 'ALERT_REMOVE';
export const ALERT_CLEAR = 'ALERT_CLEAR';
