'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CarHire1

	'''<summary>
	'''hidDefaultDriverCountryID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidDefaultDriverCountryID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidAutoSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidAutoSearch As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidCarHireResultsPage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCarHireResultsPage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''h2CarHire control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents h2CarHire As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''pSubTitle control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pSubTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divCarHireContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divCarHireContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divCarHireSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divCarHireSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddlCarHirePickUpDepotID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCarHirePickUpDepotID As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''hidCarHirePickUpDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCarHirePickUpDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''ddlCarHireDropOffDepotID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCarHireDropOffDepotID As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''hidCarHireDropOffDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCarHireDropOffDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''ddlCarHireDriverAge control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCarHireDriverAge As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''ddlCarHireLeadDriverBookingCountryID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCarHireLeadDriverBookingCountryID As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''divSelectedCar control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divSelectedCar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divCustomScript control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divCustomScript As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
