export const ENTITY_REQUEST = 'ENTITY_REQUEST';
export const ENTITY_LOAD_SUCCESS = 'ENTITY_LOAD_SUCCESS';
export const ENTITY_EDIT = 'ENTITY_EDIT';
export const ENTITY_EDIT_CANCEL = 'ENTITY_EDIT_CANCEL';
export const ENTITY_SAVE_SUCCESS = 'ENTITY_SAVE_SUCCESS';
export const ENTITY_UPDATED = 'ENTITY_UPDATED';

export const ENTITY_LOAD_LIST_REQUEST = 'ENTITY_LOAD_LIST_REQUEST';
export const ENTITY_LOAD_LIST_SUCCESS = 'ENTITY_LOAD_LIST_SUCCESS';
export const ENTITY_LIST_EDIT = 'ENTITY_LIST_EDIT';
export const ENTITY_LIST_CANCEL = 'ENTITY_LIST_CANCEL';

export const ENTITY_LOAD_CONTEXTS_REQUEST = 'ENTITY_LOAD_CONTEXTS_REQUEST';
export const ENTITY_LOAD_CONTEXTS_SUCCESS = 'ENTITY_LOAD_CONTEXTS_SUCCESS';

export const ENTITY_LOAD_MODELS_REQUEST = 'ENTITY_LOAD_MODELS_REQUEST';
export const ENTITY_LOAD_MODELS_SUCCESS = 'ENTITY_LOAD_MODELS_SUCCESS';

export const PAGE_REQUEST = 'PAGE_REQUEST';
export const PAGE_LOAD_SUCCESS = 'PAGE_LOAD_SUCCESS';
export const PAGE_ADD_CONTENT = 'PAGE_ADD_CONTENT';

export const SITE_SEARCH_PAGES_REQUEST = 'SITE_SEARCH_PAGES_REQUEST';
export const SITE_SEARCH_PAGES_LOADED = 'SITE_SEARCH_PAGES_LOADED';
export const SITE_SEARCH_TOGGLE = 'SITE_SEARCH_TOGGLE';
export const SITE_SEARCH_CHANGE_SEARCH = 'SITE_SEARCH_CHANGE_SEARCH';
