export const ADJUSTMENT_SEARCH_REQUEST = 'ADJUSTMENT_SEARCH_REQUEST';
export const ADJUSTMENT_SEARCH_RESULT = 'ADJUSTMENT_SEARCH_RESULT';

export const ALERT_ADD = 'ALERT_ADD';
export const ALERT_REMOVE = 'ALERT_REMOVE';
export const ALERT_CLEAR = 'ALERT_CLEAR';
export const ALERT_ACCEPTANCE_CHANGE = 'ALERT_ACCEPTANCE_CHANGE';

export const BASKET_CREATE_REQUEST = 'BASKET_CREATE_REQUEST';
export const BASKET_CREATE_SUCCESS = 'BASKET_CREATE_SUCCESS';
export const BASKET_LOAD_REQUEST = 'BASKET_LOAD_REQUEST';
export const BASKET_LOAD_SUCCESS = 'BASKET_LOAD_SUCCESS';
export const BASKET_UPDATED = 'BASKET_UPDATED';
export const BASKET_PREBOOK_REQUEST = 'BASKET_PREBOOK_REQUEST';
export const BASKET_PREBOOK_FLIGHT_REQUEST = 'BASKET_PREBOOK_FLIGHT_REQUEST';
export const BASKET_PREBOOK_ERROR = 'BASKET_PREBOOK_ERROR';
export const BASKET_PREBOOK_SUCCESS = 'BASKET_PREBOOK_SUCCESS';
export const BASKET_PREBOOK_FLIGHT_SUCCESS = 'BASKET_PREBOOK_FLIGHT_SUCCESS';
export const BASKET_PROMOCODE_UPDATE = 'BASKET_PROMOCODE_UPDATE';
export const BASKET_BOOK_REQUEST = 'BASKET_BOOK_REQUEST';
export const BASKET_BOOK_SUCCESS = 'BASKET_BOOK_SUCCESS';
export const BASKET_BOOK_ERROR = 'BASKET_BOOK_ERROR';
export const BASKET_UPDATE_VALUE = 'BASKET_UPDATE_VALUE';
export const BASKET_ADD_WARNING = 'BASKET_ADD_WARNING';
export const BASKET_RESET_WARNINGS = 'BASKET_RESET_WARNINGS';
export const BASKET_FLIGHT_SEAT_LOCK_RELEASED = 'BASKET_FLIGHT_SEAT_LOCK_RELEASED';

export const BOOKINGDETAILS_REQUEST = 'BOOKINGDETAILS_REQUEST';
export const BOOKINGDETAILS_SUCCESS = 'BOOKINGDETAILS_SUCCESS';

export const CANCELLATION_CHARGES_RETRIEVED = 'CANCELLATION_CHARGES_RETRIEVED';

export const EXTRA_SEARCH_REQUEST = 'EXTRA_SEARCH_REQUEST';
export const EXTRA_SEARCH_RESULT = 'EXTRA_SEARCH_RESULT';

export const QUOTE_CREATE_REQUEST = 'QUOTE_CREATE_REQUEST';
export const QUOTE_CREATE_SUCCESS = 'QUOTE_CREATE_SUCCESS';
export const QUOTE_EMAIL_SHOW = 'QUOTE_EMAIL_SHOW';
export const QUOTE_EMAIL_HIDE = 'QUOTE_EMAIL_HIDE';
export const QUOTE_RETRIEVE_REQUEST = 'QUOTE_RETRIEVE_REQUEST';
export const QUOTE_RETRIEVE_SUCCESS = 'QUOTE_RETRIEVE_SUCCESS';

export const SEARCHDETAILS_LOAD_REQUEST = 'SEARCHDETAILS_LOAD_REQUEST';
export const SEARCHDETAILS_LOAD_SUCCESS = 'SEARCHDETAILS_LOAD_SUCCESS';
export const SEARCHDETAILS_UPDATED = 'SEARCHDETAILS_UPDATED';

export const SEARCH_UPDATE_VALUE = 'SEARCH_UPDATE_VALUE';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_RESULT = 'SEARCH_RESULT';

export const SEARCHRESULTS_REQUEST = 'SEARCHRESULTS_REQUEST';
export const SEARCHRESULTS_LOAD_SUCCESS = 'SEARCHRESULTS_LOAD_SUCCESS';
export const SEARCHRESULTS_FILTER_UPDATE = 'SEARCHRESULTS_FILTER_UPDATE';
export const SEARCHRESULTS_SORT = 'SEARCHRESULTS_SORT';
export const SEARCHRESULTS_UPDATED = 'SEARCHRESULTS_UPDATED';
export const SEARCHRESULTS_UPDATE_PAGE = 'SEARCHRESULTS_UPDATE_PAGE';
export const SEARCHRESULTS_CHANGE_FLIGHT = 'SEARCHRESULTS_CHANGE_FLIGHT';
export const SEARCHRESULTS_TOGGLE_EXPANDED_SUMMARY = 'SEARCHRESULTS_TOGGLE_EXPANDED_SUMMARY';

export const SITE_REQUEST = 'SITE_REQUEST';
export const SITE_LOAD_SUCCESS = 'SITE_LOAD_SUCCESS';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
