export const SITE_REQUEST = 'SITE_REQUEST';
export const SITE_LOAD_SUCCESS = 'SITE_LOAD_SUCCESS';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
