export const CUSTOMQUERY_REQUEST = 'CUSTOMQUERY_REQUEST';
export const CUSTOMQUERY_LOAD_SUCCESS = 'CUSTOMQUERY_LOAD_SUCCESS';

export const EMAILFORM_UPDATED = 'EMAILFORM_UPDATED';
export const FORM_ADD_WARNING = 'FORM_ADD_WARNING';
export const FORM_RESET_WARNINGS = 'FORM_RESET_WARNINGS';
export const FORM_INITIALIZE = 'FORM_INITIALIZE';
export const FORM_SUBMITTED = 'FORM_SUBMITTED';
export const FORM_TOGGLE_PASSWORD = 'FORM_TOGGLE_PASSWORD';

export const SPECIALOFFERS_REQUEST = 'SPECIALOFFERS_REQUEST';
export const SPECIALOFFERS_LOAD_SUCCESS = 'SPECIALOFFERS_LOAD_SUCCESS';
export const SPECIALOFFER_LOAD_SUCCESS = 'SPECIALOFFER_LOAD_SUCCESS';
export const SPECIALOFFERS_UPDATE_PAGE = 'SPECIALOFFERS_UPDATE_PAGE';
export const SPECIALOFFERS_SORT = 'SPECIALOFFERS_SORT';
export const SPECIALOFFERS_FILTER_UPDATE = 'SPECIALOFFERS_FILTER_UPDATE';
export const SPECIALOFFERS_UPDATED = 'SPECIALOFFERS_UPDATED';

