'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompleteBookingControl

	'''<summary>
	'''divCompleteBooking control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divCompleteBooking As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hCompleteHeader control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hCompleteHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''pText control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divCompletePrices control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divCompletePrices As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''strTotalPrice control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents strTotalPrice As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''strDepositPrice control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents strDepositPrice As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''aCompleteBooking_Back control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents aCompleteBooking_Back As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''aCompleteBooking_AddComponent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents aCompleteBooking_AddComponent As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''btnCompleteBooking control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnCompleteBooking As Global.System.Web.UI.HtmlControls.HtmlInputButton

	'''<summary>
	'''hidFailURL control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidFailURL As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidRedirectURL control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidRedirectURL As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidCompleteBooking_CurrencySymbol control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCompleteBooking_CurrencySymbol As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidCompleteBooking_CurrencyPosition control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCompleteBooking_CurrencyPosition As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidInsertWarningAfter control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidInsertWarningAfter As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidWarningMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidWarningMessage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

	'''<summary>
	'''hidShowTimeoutMessage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidShowTimeoutMessage As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
