'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SunwayMaster
    
    '''<summary>
    '''Head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head As Global.Intuitive.Web.Head
    
    '''<summary>
    '''TopBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TopBody As Global.Intuitive.Web.TrackingControl
    
    '''<summary>
    '''divTopHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTopHeader As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divSubTopHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSubTopHeader As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAll As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMain As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divSubHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSubHeader As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divSidebar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSidebar As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContent As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divSidebarRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSidebarRight As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divContentLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContentLeft As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divContentFull control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContentFull As Global.Intuitive.Web.Container
    
    '''<summary>
    '''divContentExtended control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divContentExtended As Global.Intuitive.Web.Container
    
    '''<summary>
    '''BottomBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BottomBody As Global.Intuitive.Web.TrackingControl
    
    '''<summary>
    '''hidApiBaseUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidApiBaseUrl As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''divImportedScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divImportedScripts As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
