
export const BLOGLIST_LOAD_REQUEST = 'BLOGLIST_LOAD_REQUEST';
export const BLOGLIST_LOAD_SUCCESS = 'BLOGLIST_LOAD_SUCCESS';
export const BLOGLIST_FILTER_UPDATE = 'BLOGLIST_FILTER_UPDATE';
export const BLOGLIST_RESULTS_UPDATED = 'BLOGLIST_RESULTS_UPDATED';

export const CMS_REQUEST = 'CMS_REQUEST';
export const CMS_LOAD_SUCCESS = 'CMS_LOAD_SUCCESS';

export const ENTITY_REQUEST = 'ENTITY_REQUEST';
export const ENTITY_LOAD_SUCCESS = 'ENTITY_LOAD_SUCCESS';
export const ENTITY_EDIT = 'ENTITY_EDIT';
export const ENTITY_EDIT_CANCEL = 'ENTITY_EDIT_CANCEL';
export const ENTITY_SAVE_SUCCESS = 'ENTITY_SAVE_SUCCESS';
export const ENTITY_UPDATED = 'ENTITY_UPDATED';
export const ENTITY_DELETE_REQUEST = 'ENTITY_DELETE_REQUEST';
export const ENTITY_DELETED = 'ENTITY_DELETED';

export const ENTITY_LOAD_LIST_REQUEST = 'ENTITY_LOAD_LIST_REQUEST';
export const ENTITY_LOAD_LIST_SUCCESS = 'ENTITY_LOAD_LIST_SUCCESS';
export const ENTITY_LIST_EDIT = 'ENTITY_LIST_EDIT';
export const ENTITY_LIST_CANCEL = 'ENTITY_LIST_CANCEL';

export const ENTITY_LOAD_CONTEXTS_REQUEST = 'ENTITY_LOAD_CONTEXTS_REQUEST';
export const ENTITY_LOAD_CONTEXTS_SUCCESS = 'ENTITY_LOAD_CONTEXTS_SUCCESS';

export const ENTITY_LOAD_MODELS_REQUEST = 'ENTITY_LOAD_MODELS_REQUEST';
export const ENTITY_LOAD_MODELS_SUCCESS = 'ENTITY_LOAD_MODELS_SUCCESS';

export const PAGE_REQUEST = 'PAGE_REQUEST';
export const PAGE_LOAD_SUCCESS = 'PAGE_LOAD_SUCCESS';
export const PAGE_ADD_CONTENT = 'PAGE_ADD_CONTENT';

export const PROPERTIES_LOAD_REQUEST = 'PROPERTIES_LOAD_REQUEST';
export const PROPERTIES_LOAD_SUCCESS = 'PROPERTIES_LOAD_SUCCESS';
export const PROPERTIES_UPDATE_PAGE = 'PROPERTIES_UPDATE_PAGE';
export const PROPERTIES_UPDATE_SORT = 'PROPERTIES_UPDATE_SORT';

export const PROPERTY_LOAD_REQUEST = 'PROPERTY_LOAD_REQUEST';
export const PROPERTY_LOAD_SUCCESS = 'PROPERTY_LOAD_SUCCESS';

export const REDIRECT_ADD_WARNING = 'REDIRECT_ADD_WARNING';
export const REDIRECT_RESET_WARNINGS = 'REDIRECT_RESET_WARNINGS';
export const REDIRECT_EDIT = 'REDIRECT_EDIT';
export const REDIRECT_EDIT_CANCEL = 'REDIRECT_EDIT_CANCEL';
export const REDIRECT_LOAD_LIST_SUCCESS = 'REDIRECT_LOAD_LIST_SUCCESS';
export const REDIRECT_LOAD_LIST_REQUEST = 'REDIRECT_REQUEST';
export const REDIRECT_DISPLAY = 'REDIRECT_DISPLAY';
export const REDIRECT_DISPLAY_CANCEL = 'REDIRECT_DISPLAY_CANCEL';
export const REDIRECT_SELECT = 'REDIRECT_SELECT';
export const REDIRECT_UPDATED = 'REDIRECT_UPDATED';

export const SITE_SEARCH_PAGES_REQUEST = 'SITE_SEARCH_PAGES_REQUEST';
export const SITE_SEARCH_PAGES_LOADED = 'SITE_SEARCH_PAGES_LOADED';
export const SITE_SEARCH_TOGGLE = 'SITE_SEARCH_TOGGLE';
export const SITE_SEARCH_CHANGE_SEARCH = 'SITE_SEARCH_CHANGE_SEARCH';

export const TWITTER_USER_TWEETS_REQUEST = 'TWITTER_USER_TWEETS_REQUEST';
export const TWITTER_USER_TWEETS_LOADED = 'TWITTER_USER_TWEETS_LOADED';
