'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LeadGuestDetailsControl

	'''<summary>
	'''divLeadGuestDetails control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divLeadGuestDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''h2LeadGuestDetails control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents h2LeadGuestDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddlLeadGuestDetails_Title control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlLeadGuestDetails_Title As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''txtLeadGuestDetails_FirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_FirstName As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''txtLeadGuestDetails_LastName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_LastName As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''txtLeadGuestDetails_Email control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_Email As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''txtLeadGuestDetails_RepeatEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_RepeatEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''trPostcodeLookup control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents trPostcodeLookup As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''txtPostcodeLookup_Postcode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtPostcodeLookup_Postcode As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''txtLeadGuestDetails_Address control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_Address As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''txtLeadGuestDetails_City control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_City As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''trPostCode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents trPostCode As Global.System.Web.UI.HtmlControls.HtmlTableRow

	'''<summary>
	'''lblLeadGuestDetails_Postcode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblLeadGuestDetails_Postcode As Global.System.Web.UI.HtmlControls.HtmlTableCell

	'''<summary>
	'''txtLeadGuestDetails_Postcode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_Postcode As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''ddlLeadGuestDetails_BookingCountry control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlLeadGuestDetails_BookingCountry As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''txtLeadGuestDetails_PhoneNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_PhoneNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''txtLeadGuestDetails_MobileNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLeadGuestDetails_MobileNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

	'''<summary>
	'''hidLeadGuestDetails_ValidationExclude control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidLeadGuestDetails_ValidationExclude As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
