'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HotelResultsFooterControl
    
    '''<summary>
    '''divHotelResultsFooterControls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHotelResultsFooterControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''divPagingBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPagingBottom As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pagingBottom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagingBottom As Global.Intuitive.Web.Controls.Paging
    
    '''<summary>
    '''btnBackToTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackToTop As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''pDisclaimerText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDisclaimerText As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
