'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MyBookingsPayment

	'''<summary>
	'''divPaymentDetails control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divPaymentDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hPayment_Title control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hPayment_Title As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''pPayment_Text control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pPayment_Text As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divPaymentDetailsWarning control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divPaymentDetailsWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''spnMyBookingsPaymentTotalPrice control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spnMyBookingsPaymentTotalPrice As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''spnMyBookingsPaymentTotalPaid control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spnMyBookingsPaymentTotalPaid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''spnMyBookingsPaymentTotalOutstanding control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spnMyBookingsPaymentTotalOutstanding As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''dlCardDetails control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dlCardDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddlCCCardTypeID control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCCardTypeID As Global.Intuitive.Web.Controls.Dropdown

	'''<summary>
	'''dtStartDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtStartDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddStartDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddStartDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddlCCStartMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCStartMonth As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''ddlCCStartYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCStartYear As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''ddlCCExpireMonth control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCExpireMonth As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''ddlCCExpireYear control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlCCExpireYear As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''dtIssueNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dtIssueNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddIssueNumber control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddIssueNumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''spnAddress1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spnAddress1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''spnAddress2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spnAddress2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''spnTownCity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spnTownCity As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''spnPostcode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents spnPostcode As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hidAddress1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidAddress1 As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidAddress2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidAddress2 As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidTownCity control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidTownCity As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidPostcode control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidPostcode As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''btnPayBalance control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnPayBalance As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''hidCSVTooltipText control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCSVTooltipText As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidAmount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidAmount As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidSurcharge control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidSurcharge As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidSurchargePercentage control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidSurchargePercentage As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidCurrencySymbol control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCurrencySymbol As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''hidCurrencyPosition control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hidCurrencyPosition As Global.Intuitive.WebControls.Hidden

	'''<summary>
	'''pPaymentDetailsSending control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pPaymentDetailsSending As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''pPaymentDetailsSent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pPaymentDetailsSent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''pPaymentDetailsNotSent control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pPaymentDetailsNotSent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
