'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SearchSummaryControl

	'''<summary>
	'''divSearchSummary control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divSearchSummary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''hSummary control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents hSummary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''divSearchSummaryControls control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divSearchSummaryControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''pagingTop control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents pagingTop As Global.Intuitive.Web.Controls.Paging

	'''<summary>
	'''divSortOrder control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divSortOrder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''lblSortBy control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblSortBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''ddlSortOrder control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ddlSortOrder As Global.Intuitive.WebControls.DropDown

	'''<summary>
	'''divSearchSummaryViewTabs control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divSearchSummaryViewTabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''aMapView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents aMapView As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''aQuickView control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents aQuickView As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''aPopular control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents aPopular As Global.System.Web.UI.HtmlControls.HtmlAnchor

	'''<summary>
	'''divPopularHelper control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divPopularHelper As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
