export const FILTER_TYPES = {
    ID: 'ID',
    TEXT: 'TEXT',
    ARRAY: 'ARRAY',
    RESULTS_RANGE: 'RESULTS_RANGE',
    SUB_RESULTS_ID: 'SUB_RESULTS_ID',
    SUB_RESULTS_RANGE: 'SUB_RESULTS_RANGE',
};

export const FLIGHT_PLUS_HOTEL_TYPES = {
    FLIGHTONLY: 'FLIGHTONLY',
    SEPARATE: 'SEPARATE',
    PACKAGEPRICE: 'PACKAGEPRICE',
    PACKAGESEARCH: 'PACKAGESEARCH',
};
